import Blogs from "@/components/sections/Blog";
import Hero from "@/components/sections/hero";
import Testimonials from "@/components/sections/testimonials";
import TreatmentReels from "@/components/sections/TreatmentReels";
import ChiropracticClinic from "@/components/sections/treatments";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Best chiropractic :Dr. Rajneesh Kant",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
     <Hero/>
     <ChiropracticClinic/>
     <TreatmentReels/>
     <Blogs/>
     <Testimonials/>
    </main>
  );
}
 