
import AuthSystem from '@/page_/auth/AuthSystem'
import React from 'react'

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign in and Sign up at:Dr. Rajneesh Kant",
  description: "Generated by create next app",
};
const Page = () => {
  return <AuthSystem/>
}

export default Page 